# Generated by Django 4.2.7 on 2023-11-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugar',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='lugar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='texto',
            field=models.CharField(max_length=5000),
        ),
    ]
