# Generated by Django 4.2.7 on 2023-11-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0002_rename_nome_lugar_titulo_alter_lugar_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='texto',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='titulo',
            field=models.TextField(max_length=200),
        ),
    ]
