# Generated by Django 4.2.7 on 2023-11-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0004_alter_lugar_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugar',
            old_name='id',
            new_name='id_lugar',
        ),
    ]
