# Generated by Django 4.2.7 on 2023-11-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0005_rename_id_lugar_id_lugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugar',
            old_name='id_lugar',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='lugar',
            name='texto',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
