# Generated by Django 4.2.7 on 2023-11-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0007_alter_lugar_texto_alter_lugar_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugar',
            old_name='id',
            new_name='id_lugar',
        ),
    ]
