# Generated by Django 4.2.7 on 2023-11-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0010_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lugar',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.CharField(max_length=300),
        ),
    ]
