# Generated by Django 4.2.7 on 2023-12-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0011_delete_lugar_alter_usuario_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id_lead', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField()),
                ('assunto', models.TextField()),
            ],
        ),
    ]
