# Generated by Django 4.2.7 on 2023-12-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0012_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assunto',
            field=models.TextField(max_length=1000),
        ),
    ]
